name: travel_in_app
description: Travel In - Yemen Travel & Mobility Super App (Phase 1 MVP)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  qr_flutter: ^4.1.0
  supabase_flutter: ^2.8.0

flutter:
  uses-material-design: true
